# -*- coding: utf-8 -*-
"""casualimpact (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDCmICutSlayKfxJM5UQh5LuVXLHYhyr
"""

!pip install pycausalimpact

import pandas as pd
from causalimpact import CausalImpact
import matplotlib.pyplot as plt

# R 패키지에서 사용하는 원본 데이터셋(JHU 데이터)을 불러옵니다.
url = "https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv"
df = pd.read_csv(url)

# 날짜 형식 변환
df['date'] = pd.to_datetime(df['date'])

# 분석 기간 및 국가 설정
start_date = '2020-01-22'
treat_date = '2020-02-28' # 개입 시점 (거리두기 시작 등)
end_date = '2020-05-01'

target_countries = ['Korea, South', 'Canada', 'Greece', 'US', 'Japan']

# 데이터 필터링 (확진자 & 특정 국가 & 기간)
df_filtered = df[
    (df['type'] == 'confirmed') &
    (df['country'].isin(target_countries)) &
    (df['date'] >= start_date) &
    (df['date'] <= end_date)
].copy()

# 국가명 변경 ('Korea, South' -> 'Korea') : R 코드와 동일하게
df_filtered['country'] = df_filtered['country'].replace('Korea, South', 'Korea')

# 날짜별, 국가별 확진자 수 합계 (Group by)
df_grouped = df_filtered.groupby(['date', 'country'])['cases'].sum().reset_index()


df_final = df_grouped.pivot(index='date', columns='country', values='cases')
df_final = df_final.fillna(0)
cols = ['Korea'] + [c for c in df_final.columns if c != 'Korea']
df_final = df_final[cols]
print("--- 준비된 데이터 (상위 5행) ---")
print(df_final.head())

# 4. CausalImpact 실행
# 사전(Pre) 및 사후(Post) 기간 설정
pre_period = [start_date, treat_date]
post_period = [pd.to_datetime(treat_date) + pd.Timedelta(days=1), end_date]

# 모델 실행
ci = CausalImpact(df_final, pre_period, post_period)

# 5. 결과 리포트 및 시각화
# (1) 요약 통계 출력
print("\n--- 분석 요약 (Summary) ---")
print(ci.summary())
# (2) 상세 리포트 출력
print("\n--- 상세 리포트 (Report) ---")
print(ci.summary(output='report'))
# (3) 그래프 그리기
# R의 plot(causal_impact)와 동일
ci.plot()

ci = CausalImpact(df_final, pre_period, post_period)
ci.summary()